# app.py
import os
import sys

# Add project root to path for module imports
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# Standard libraries
import streamlit as st
import plotly.graph_objects as go
import numpy as np
import polars as pl
import datetime
import logging
from typing import Dict, Any, List, Tuple, Union, Optional

# Project-specific imports
from src.data_transformation.transformation_pipeline import transformation_pipeline
from src.data_extraction.dataframe_loader import load_data
from src.data_modeling.surface_lgbm_modeling import (
    load_surface_models,
    _to_date,
    HORIZONS,
    predict_surface,
)
from src.data_modeling.vol_surface_visualization import generate_vol_surface

# Configure logger
logger = logging.getLogger(__name__)
if not logger.hasHandlers():
    logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")

# -----------------------------------------------------------------------------
# About text
# -----------------------------------------------------------------------------
ABOUT_TEXT = r"""
### What Is an Option and Why Does Volatility Matter?

An **option** is a contract giving the right—but not the obligation—to buy or sell a stock at a fixed price on or before a certain date.

Options are priced largely based on **volatility**, which measures how much the stock's price moves. Higher volatility raises the chance of large price swings, making options more expensive.


---


### Implied vs. Local Volatility Surfaces

- **Implied volatility** is the market's expectation of future volatility, backed out of option prices across strikes and expiries.

- A **local volatility surface** goes deeper: it asks

  > *"What instantaneous volatility at each stock price and future date would make today's option prices consistent under a risk‑neutral model?"*

  One inverts the option pricing model (Dupire's formula) to recover this surface, which is essential for pricing more complex derivatives.


---


### Realized Local Volatility Surface

The **Realized Local Volatility Surface (RLVS)** brings these ideas to historical data:


1. **Realized volatility** is what actually happened: how much the stock price varied over a past window.

2. A simple realized‑vol curve is only a single line for the one path the stock took.

3. The RLVS estimates the conditional expectation

   $$
   \sigma_{\mathrm{real}}(K, T)
   \;=\;
   \mathbb{E}\bigl[\mathrm{RealizedVol}\,\bigm|\tfrac{S_T}{S_0}=e^{k}\bigr],
   $$

   where $K = S_0 e^{k}$ is the strike and $T$ is the time to expiry.

   It tells you,

   > *"Had the stock ended at strike \(K\) in \(T\) days, what volatility would we have realized?"*


---


This app lets you compare that **historical conditional vol surface** (generated by the ML model) to the actual **realized volatility points** observed historically for specific outcomes.

"""

def create_plotly_figure(
    K_mesh: np.ndarray,
    T_mesh: np.ndarray,
    Z: np.ndarray,
    today_data: pl.DataFrame,  # Single row DataFrame for the specific date
    stock: str,
    trade_date: datetime.date,
    loaded_horizons: List[int]  # Actual horizons used
) -> go.Figure:
    """
    Creates the Plotly 3D surface plot with overlays and custom hover text.
    
    Args:
        K_mesh: 2D array of strike prices for surface mesh
        T_mesh: 2D array of time horizons for surface mesh
        Z: 2D array of volatility values for surface mesh
        today_data: DataFrame with single row of data for the selected date
        stock: Stock symbol
        trade_date: Selected trading date
        loaded_horizons: List of time horizons (in trading days)
        
    Returns:
        A Plotly Figure object with the 3D volatility surface
    """
    fig = go.Figure()

    # Extract S0 (current stock price) and row data
    S0 = np.nan
    row_dict = {}
    if today_data is not None and not today_data.is_empty():
        row_dict = today_data.row(0, named=True)
        S0 = row_dict.get("close", np.nan)
        if np.isnan(S0): 
            logger.warning("S0 is NaN, k calculations will fail.")

    # Initialize data arrays for realized points and S0 line
    realized_strikes, realized_T, realized_sigma = [], [], []
    realized_k = []  # For hover text on realized points
    s0_line_T, s0_line_sigma_hist = [], []  # For historical realized vol at S0 line

    # Calculate k values (log moneyness) from strike prices
    k_mesh = np.full_like(K_mesh, np.nan)
    if S0 is not None and np.isfinite(S0) and S0 > 0:
        with np.errstate(divide='ignore', invalid='ignore'):
            k_mesh = np.log(K_mesh / S0)
        k_mesh[~np.isfinite(k_mesh)] = np.nan

    # Extract realized volatility data points if available
    if row_dict and not np.isnan(S0) and S0 > 0:
        for h in loaded_horizons:
            # Convert trading days to calendar days
            Tcal = int(round(h * 7/5))

            # 1. Extract data for realized points overlay (uses FUTURE volatility)
            rv_future_col = f"rv_{h}d_future"
            lr_future_col = f"log_ret_future_{h}"
            if rv_future_col in row_dict and lr_future_col in row_dict:
                rv_fut = row_dict[rv_future_col]
                lr_fut = row_dict[lr_future_col]
                if rv_fut is not None and lr_fut is not None and np.isfinite(rv_fut) and np.isfinite(lr_fut) and rv_fut >= 0:
                    try:
                        # Calculate annualized volatility
                        sigma0_fut = np.sqrt(rv_fut / (h / 252.0))
                        realized_strikes.append(S0 * np.exp(lr_fut))
                        realized_T.append(Tcal)
                        realized_sigma.append(sigma0_fut)
                        realized_k.append(lr_fut)
                    except Exception as e: 
                        logger.warning(f"Error calculating realized overlay pt H={h}: {e}")

            # 2. Extract data for S0 line (uses HISTORICAL volatility)
            rv_hist_col = f"rv_{h}d"  # Historical realized vol column
            rv_for_s0_line = row_dict.get(rv_hist_col)
            if rv_for_s0_line is not None and np.isfinite(rv_for_s0_line) and rv_for_s0_line >= 0:
                try:
                    # Calculate annualized volatility from historical RV
                    sigma0_hist_at_S0 = np.sqrt(rv_for_s0_line / (h / 252.0))
                    s0_line_T.append(Tcal)
                    s0_line_sigma_hist.append(sigma0_hist_at_S0)
                except Exception as e: 
                    logger.warning(f"Error calculating S0 line sigma H={h}: {e}")

    # Calculate dynamic axis ranges for better visualization
    z_min_data = np.inf
    z_max_data = -np.inf
    
    # Collect all z values for range calculation
    all_z_values = []
    if Z is not None and Z.size > 0: 
        all_z_values.extend(Z[~np.isnan(Z)].flatten())
    if realized_sigma: 
        all_z_values.extend(realized_sigma)
    if s0_line_sigma_hist: 
        all_z_values.extend(s0_line_sigma_hist)
        
    if all_z_values:
        z_min_data = np.nanmin(all_z_values)
        z_max_data = np.nanmax(all_z_values)
        
    # Set z-axis limits with padding
    z_axis_min = max(0.0, z_min_data * 0.85 if np.isfinite(z_min_data) else 0.0)
    z_axis_max = z_max_data * 1.15 if np.isfinite(z_max_data) else z_axis_min + 0.5

    # Calculate x-axis range based on strikes
    x_min_real_factors = np.inf
    x_max_real_factors = -np.inf
    
    # Collect all x values for range calculation
    all_x_values_for_range = []
    if S0 is not None and np.isfinite(S0): 
        all_x_values_for_range.append(S0)
    if realized_strikes: 
        all_x_values_for_range.extend(realized_strikes)
        
    if all_x_values_for_range:
        x_min_real_factors = np.nanmin(all_x_values_for_range) * 0.85
        x_max_real_factors = np.nanmax(all_x_values_for_range) * 1.15
        
    x_axis_min = max(0.0, x_min_real_factors if np.isfinite(x_min_real_factors) else 0.0)
    x_axis_max = x_max_real_factors if np.isfinite(x_max_real_factors) else x_axis_min + 10.0
    
    if x_axis_max <= x_axis_min: 
        x_axis_max = x_axis_min * 1.1 if x_axis_min > 0 else 10.0

    # Configure contour settings for the surface
    contour_settings = {
        "x": {"show": False}, 
        "y": {"show": False},
        "z": {"show": True, "highlight": True, "highlightcolor": "limegreen", "project": {"z": True}}
    }

    # Add the main volatility surface trace
    fig.add_trace(go.Surface(
        x=K_mesh, y=T_mesh, z=Z,
        name="Predicted Surface", showlegend=True,
        colorscale="Viridis",
        colorbar=dict(title='Ann. Vol (σ)', thickness=20, len=0.75),
        contours=contour_settings,
        # Simplified hover template showing only the necessary values
        hovertemplate="<b>Strike K:</b> %{x:.2f}<br>" +
                      "<b>T:</b> %{y:.0f} cd<br>" +
                      "<b>Predicted σ:</b> %{z:.4f}<extra></extra>",
        lighting=dict(ambient=0.7, diffuse=0.7, specular=0.2)
    ))

    # Add realized volatility points if available
    if realized_strikes:
        fig.add_trace(go.Scatter3d(
            x=realized_strikes, y=realized_T, z=realized_sigma,
            mode="markers", marker=dict(color="red", size=5, symbol='diamond'),
            name="Realized Points", showlegend=True,
            hovertemplate="<b>Strike K:</b> %{x:.2f}<br>" +
                          "<b>T:</b> %{y:.0f} cd<br>" +
                          "<b>Realized σ:</b> %{z:.4f}<extra></extra>"
        ))
        logger.info(f"Plotting {len(realized_strikes)} realized points.")
    else: 
        logger.info("No realized points available to plot.")

    # Add S0 line (historical realized vol at current spot price)
    if S0 is not None and np.isfinite(S0) and s0_line_T:
        # Sort points by time for a smooth line
        s0_line_points = sorted(zip(s0_line_T, s0_line_sigma_hist))
        s0_T_sorted = [p[0] for p in s0_line_points]
        s0_sigma_sorted = [p[1] for p in s0_line_points]
        
        fig.add_trace(go.Scatter3d(
            x=[S0] * len(s0_T_sorted),   # Constant K = S0
            y=s0_T_sorted,               # T values
            z=s0_sigma_sorted,           # Historical realized sigma at S0
            mode='lines+markers',
            marker=dict(color='cyan', size=3),
            line=dict(color='cyan', width=4),
            name=f'Hist. RV @ Spot K={S0:.2f}',
            showlegend=True,
            hovertemplate="<b>Strike K:</b> %{x:.2f} (Spot)<br>" +
                          "<b>T:</b> %{y:.0f} cd<br>" +
                          "<b>Hist. RV σ:</b> %{z:.4f}<extra></extra>"
        ))
        logger.info(f"Adding S0 line with {len(s0_T_sorted)} historical RV points.")
    else: 
        logger.warning("Could not plot S0 line (missing S0 or historical RV data).")

    # Configure overall plot layout
    fig.update_layout(
        title=f"{stock} Predicted Volatility Surface @ {trade_date}",
        scene=dict(
            xaxis_title="Strike Price (K)", 
            yaxis_title="Time to Maturity (Calendar Days, T)", 
            zaxis_title="Annualized Volatility (σ)",
            xaxis_range=[x_axis_min, x_axis_max],
            zaxis_range=[z_axis_min, z_axis_max],
            aspectratio=dict(x=1.5, y=1.5, z=1)
        ),
        margin=dict(l=10, r=10, b=10, t=50),
        legend=dict(yanchor="top", y=0.99, xanchor="left", x=0.01)
    )
    
    # Set default camera angle for better visualization
    fig.update_layout(scene_camera=dict(eye=dict(x=1.7, y=-1.7, z=1.0)))

    return fig

def main():
    """
    Main function that sets up the Streamlit app interface and handles user interaction.
    """
    st.set_page_config(page_title="Volatility Surface App", layout="wide")

    # Create tabs for visualization and information
    viz_tab, about_tab = st.tabs(["Visualizer", "About"])

    # About tab content
    with about_tab:
        st.markdown(ABOUT_TEXT, unsafe_allow_html=False)

    # Visualization tab content
    with viz_tab:
        st.title("Volatility Surface Visualizer")
        st.markdown("Visualize the LGBM modeled volatility surface, compared to realized points.")

        # Load available stock symbols
        symbols = ["AAPL", "MSFT", "GOOGL", "NVDA", "AMD", "TSLA"]  # Default list
        try:
            # Try to load custom symbols list from file
            symbols_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'processed', 'symbols.txt')
            if os.path.exists(symbols_path):
                with open(symbols_path) as f:
                    symbols = sorted([s.strip() for s in f if s.strip()])
            else:
                st.warning(f"symbols.txt not found at {symbols_path}, using default.")
        except Exception as e:
            st.warning(f"Could not load symbols file: {e}. Using default.")
            logger.warning(f"Could not load symbols file: {e}")

        # Sidebar inputs for user parameters
        st.sidebar.header("Surface Parameters")
        stock = st.sidebar.selectbox("Stock Symbol", symbols, 
                                    index=symbols.index("AAPL") if "AAPL" in symbols else 0)
        default_date = datetime.date(2021, 1, 25)
        trade_date = st.sidebar.date_input("Trade Date", default_date)
        generate = st.sidebar.button("Generate Surface Plot", key="generate_button")

        # Main content area - generate surface when button is clicked
        if generate:
            with st.spinner(f"Generating surface for {stock} on {trade_date}..."):
                try:
                    # Step 1: Load historical price data
                    logger.info(f"Loading OHLCV data for {stock}...")
                    ohlcv_data = load_data("ohlcv", stock)
                    if isinstance(ohlcv_data, pl.DataFrame):
                        ohlcv_df = ohlcv_data
                    else:
                        ohlcv_df = pl.from_pandas(ohlcv_data)
                    logger.info("OHLCV data loaded.")

                    # Step 2: Apply feature engineering pipeline
                    logger.info("Applying transformation pipeline...")
                    transformed_df = transformation_pipeline(ohlcv_df)
                    logger.info("Transformation complete.")

                    # Step 3: Load pre-trained ML models
                    logger.info("Loading surface models...")
                    models_dict = load_surface_models()  # Loads latest models
                    logger.info(f"Models loaded from: {models_dict.get('model_dir', 'N/A')}")

                    # Step 4: Generate volatility surface prediction
                    logger.info(f"Predicting surface for {stock} on {trade_date}...")
                    surface_data = predict_surface(
                        model_dict=models_dict,
                        df=transformed_df,
                        stock=stock,
                        trade_date=trade_date
                    )

                    # Step 5: Create and display the visualization
                    if surface_data:
                        logger.info("Surface data generated, creating plot...")
                        K_mesh, T_mesh, Z = surface_data

                        # Get data row for the selected date from transformed data
                        today_data_row = transformed_df.filter(
                            (pl.col("act_symbol") == stock) & 
                            (pl.col("date").cast(pl.Date) == trade_date)
                        ).head(1)

                        if today_data_row.is_empty():
                            st.error(f"Data for {stock} on {trade_date} not found in transformed data.")
                            logger.error(f"Data for {stock}/{trade_date} missing post-transformation.")
                        else:
                            # Create and display the 3D surface plot
                            loaded_horizons = models_dict.get("horizons", HORIZONS)
                            fig = create_plotly_figure(
                                K_mesh, T_mesh, Z,
                                today_data_row,
                                stock, trade_date,
                                loaded_horizons
                            )
                            st.plotly_chart(fig, use_container_width=True)
                            logger.info("Plot displayed.")
                    else:
                        st.error(f"Failed to generate surface data for {stock} on {trade_date}.")
                        logger.error(f"predict_surface returned None for {stock} on {trade_date}.")

                except FileNotFoundError as fnf:
                    st.error(f"Error: Required file not found. Details: {fnf}")
                    logger.error(f"FileNotFoundError: {fnf}", exc_info=True)
                except ImportError as ime:
                    st.error(f"Error: Could not import necessary modules. Details: {ime}")
                    logger.error(f"ImportError: {ime}", exc_info=True)
                except Exception as e:
                    st.error(f"An unexpected error occurred: {e}")
                    logger.error(f"Unexpected error in Streamlit app: {e}", exc_info=True)
        else:
            st.info("Select parameters in the sidebar and click 'Generate Surface Plot'.")

if __name__ == "__main__":
    main()